HAILO Python Environment working.
Just getting an error AttributeError: 'InferVStreams' object has no attribute 'input_vstreams'.

Need to study the HAILO Python documentation